stages:
  - assembly
  - test
  - release

cache:
  paths:
    - $HOME/.gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - java -version
  - ./gradlew -version

assembly:
  stage: assembly
  image: bellsoft/liberica-openjdk-alpine-musl:14
  script: ./gradlew --build-cache assemble
  only:
    - master
  artifacts:
    paths:
      - .gradle/
      - build/
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle

test:liberica-14:
  stage: test
  image: bellsoft/liberica-openjdk-alpine-musl:14
  script: ./gradlew check --scan
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .gradle
  artifacts:
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

test:adoptopenjdk-14:
  stage: test
  image: adoptopenjdk/openjdk14:alpine-slim
  script: ./gradlew check --scan
  artifacts:
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

test:openjdk-14:
  stage: test
  image: openjdk:14-alpine
  script: ./gradlew check --scan
  artifacts:
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

test:openjdk-15:
  stage: test
  image: openjdk:15-alpine
  script: ./gradlew check --scan
  artifacts:
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

release:
  stage: release
  image: bellsoft/liberica-openjdk-alpine-musl:14
  only:
    - master
  dependencies:
    - assembly
  script: ./gradlew bintrayUpload
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .gradle
