image: bellsoft/liberica-openjdk-alpine-musl:14.0.1

include:
  - template: Dependency-Scanning.gitlab-ci.yml

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - java -version
  - ./gradlew -version

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle

security_scan:
  stage: test
  script: ./gradlew gemnasiumDumpDependencies
  allow_failure: true
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .gradle
  artifacts:
    reports:
      dependency_scanning: ./**/reports/gradle-dependencies.json

test:
  stage: test
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .gradle
  artifacts:
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

deploy:
  stage: deploy
  only:
    - master
  script: ./gradlew bintrayUpload
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - .gradle
