# default rules: https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml

style:
   ReturnCount:
      active: false
   ThrowsCount:
      active: false
   MaxLineLength:
      maxLineLength: 150
   UnusedImports:
      active: true
