# default rules: https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  MaximumLineLength:
    maxLineLength: 150
  CommentSpacing:
    active: false
  NoMultipleSpaces:
    active: false

style:
  ReturnCount:
    active: false
  ThrowsCount:
    active: false
  MaxLineLength:
    maxLineLength: 150
  UnusedImports:
    active: true
